# Generated by generate_iac_templates.py
# IAM roles migrated from SAML federation to AAM trust policy.

variable "trust_service_principal" {
  description = "The service principal for the new trust relationship"
  type        = string
  default     = "account-access-preview.amazonaws.com"
}

data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "aam_trust" {
  statement {
    sid     = "AAMTrustPolicyStatement"
    effect  = "Allow"
    actions = ["sts:AssumeRole", "sts:SetContext"]

    principals {
      type        = "Service"
      identifiers = [var.trust_service_principal]
    }
  }
}

resource "aws_iam_role" "entra_admin" {
  name               = "Entra_Admin"
  assume_role_policy = data.aws_iam_policy_document.aam_trust.json

  tags = {
    ManagedBy = "AAM-Migration"
  }
}

resource "aws_iam_role_policy_attachment" "entra_admin_attach_0" {
  role       = aws_iam_role.entra_admin.name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}

resource "aws_iam_role" "entra_security" {
  name               = "Entra_Security"
  assume_role_policy = data.aws_iam_policy_document.aam_trust.json

  tags = {
    ManagedBy = "AAM-Migration"
  }
}

resource "aws_iam_role_policy_attachment" "entra_security_attach_0" {
  role       = aws_iam_role.entra_security.name
  policy_arn = "arn:aws:iam::aws:policy/SecurityAudit"
}

resource "aws_iam_role" "extra_readonly" {
  name               = "Extra_ReadOnly"
  assume_role_policy = data.aws_iam_policy_document.aam_trust.json

  tags = {
    ManagedBy = "AAM-Migration"
  }
}

# Outputs
output "entra_admin_arn" {
  description = "ARN of Entra_Admin"
  value       = aws_iam_role.entra_admin.arn
}

output "entra_security_arn" {
  description = "ARN of Entra_Security"
  value       = aws_iam_role.entra_security.arn
}

output "extra_readonly_arn" {
  description = "ARN of Extra_ReadOnly"
  value       = aws_iam_role.extra_readonly.arn
}

