#!/usr/bin/env python3
"""
Generate CloudFormation and Terraform templates from AAM role evaluation CSV.

Reads the CSV produced by AAM_role_evaluation.py and generates IaC templates
that customers can check into their pipelines to recreate the roles with the
new trust policy (AAM / Identity Center trust).

Usage:
    python generate_iac_templates.py <csv_file>

Example:
    python generate_iac_templates.py AAM_role_evaluation_760560298386.csv

Outputs:
    - aam_roles_cloudformation.yaml
    - aam_roles_terraform.tf
"""

import csv
import json
import sys
import os
import re
from collections import defaultdict
from typing import Dict, List, Any


# ---------------------------------------------------------------------------
# The new trust policy that roles should have after migration
# ---------------------------------------------------------------------------
NEW_TRUST_POLICY = {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AAMTrustPolicyStatement",
            "Effect": "Allow",
            "Principal": {
                "Service": "account-access.amazonaws.com"
            },
            "Action": ["sts:AssumeRole", "sts:SetContext"],
        }
    ],
}


def sanitize_logical_id(name: str) -> str:
    """Convert a role name to a valid CloudFormation logical ID (alphanumeric only)."""
    return re.sub(r"[^a-zA-Z0-9]", "", name)


def sanitize_tf_resource_name(name: str) -> str:
    """Convert a role name to a valid Terraform resource name (lowercase, underscores)."""
    return re.sub(r"[^a-z0-9_]", "_", name.lower())


def parse_csv(csv_file: str) -> Dict[str, List[Dict[str, str]]]:
    """
    Parse the evaluation CSV and group policies by role name.
    Returns: {role_name: [{"policy_name": ..., "policy_type": ...}, ...]}
    """
    roles: Dict[str, List[Dict[str, str]]] = defaultdict(list)
    with open(csv_file, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            role_name = row["Role Name"].strip()
            policy_name = row["Policy Name"].strip()
            policy_type = row["Policy Type"].strip()
            if policy_name != "(none)":
                roles[role_name].append(
                    {"policy_name": policy_name, "policy_type": policy_type}
                )
            else:
                # Ensure the role entry exists even with no policies
                if role_name not in roles:
                    roles[role_name] = []
    return dict(roles)


# ---------------------------------------------------------------------------
# CloudFormation Generation
# ---------------------------------------------------------------------------

def generate_cloudformation(roles: Dict[str, List[Dict[str, str]]], output_file: str) -> None:
    """Generate a CloudFormation YAML template for the roles."""
    lines = []
    lines.append("AWSTemplateFormatVersion: '2010-09-09'")
    lines.append("Description: >-")
    lines.append("  IAM roles migrated from SAML federation to AAM trust policy.")
    lines.append("  Generated by generate_iac_templates.py")
    lines.append("")
    lines.append("Parameters:")
    lines.append("  TrustServicePrincipal:")
    lines.append("    Type: String")
    lines.append("    Default: account-access.amazonaws.com")
    lines.append("    Description: The service principal for the new trust relationship.")
    lines.append("")
    lines.append("Resources:")

    for role_name, policies in roles.items():
        logical_id = sanitize_logical_id(role_name) + "Role"
        lines.append("")
        lines.append(f"  {logical_id}:")
        lines.append("    Type: AWS::IAM::Role")
        lines.append("    Properties:")
        lines.append(f"      RoleName: {role_name}")
        lines.append("      AssumeRolePolicyDocument:")
        lines.append("        Version: '2012-10-17'")
        lines.append("        Statement:")
        lines.append("          - Sid: AAMTrustPolicyStatement")
        lines.append("            Effect: Allow")
        lines.append("            Principal:")
        lines.append("              Service: !Ref TrustServicePrincipal")
        lines.append("            Action:")
        lines.append("              - sts:AssumeRole")
        lines.append("              - sts:SetContext")

        # Managed policies
        managed = [p for p in policies if p["policy_type"] != "Inline"]
        if managed:
            lines.append("      ManagedPolicyArns:")
            for p in managed:
                if p["policy_type"] == "AWS Managed":
                    lines.append(f"        - arn:aws:iam::aws:policy/{p['policy_name']}")
                else:
                    # Customer managed — use account-relative ARN
                    lines.append(f"        - !Sub arn:aws:iam::${{AWS::AccountId}}:policy/{p['policy_name']}")

        # Inline policies — we note them but can't reconstruct the document from the CSV
        inline = [p for p in policies if p["policy_type"] == "Inline"]
        if inline:
            lines.append("      Policies:")
            for p in inline:
                lines.append(f"        - PolicyName: {p['policy_name']}")
                lines.append("          PolicyDocument:")
                lines.append("            Version: '2012-10-17'")
                lines.append("            Statement:")
                lines.append("              - Sid: TODO")
                lines.append("                Effect: Allow")
                lines.append("                Action:")
                lines.append("                  - '*'  # TODO: Replace with actual inline policy document")
                lines.append("                Resource: '*'")

        lines.append("      Tags:")
        lines.append("        - Key: ManagedBy")
        lines.append("          Value: AAM-Migration")

    lines.append("")
    lines.append("Outputs:")
    for role_name in roles:
        logical_id = sanitize_logical_id(role_name) + "Role"
        lines.append(f"  {logical_id}Arn:")
        lines.append(f"    Description: ARN of {role_name}")
        lines.append(f"    Value: !GetAtt {logical_id}.Arn")

    with open(output_file, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"  CloudFormation template: {output_file}")


# ---------------------------------------------------------------------------
# Terraform Generation
# ---------------------------------------------------------------------------

def generate_terraform(roles: Dict[str, List[Dict[str, str]]], output_file: str) -> None:
    """Generate a Terraform configuration file for the roles."""
    lines = []
    lines.append('# Generated by generate_iac_templates.py')
    lines.append('# IAM roles migrated from SAML federation to AAM trust policy.')
    lines.append('')
    lines.append('variable "trust_service_principal" {')
    lines.append('  description = "The service principal for the new trust relationship"')
    lines.append('  type        = string')
    lines.append('  default     = "account-access.amazonaws.com"')
    lines.append('}')
    lines.append('')
    lines.append('data "aws_caller_identity" "current" {}')
    lines.append('')

    # Trust policy document (shared)
    lines.append('data "aws_iam_policy_document" "aam_trust" {')
    lines.append('  statement {')
    lines.append('    sid     = "AAMTrustPolicyStatement"')
    lines.append('    effect  = "Allow"')
    lines.append('    actions = ["sts:AssumeRole", "sts:SetContext"]')
    lines.append('')
    lines.append('    principals {')
    lines.append('      type        = "Service"')
    lines.append('      identifiers = [var.trust_service_principal]')
    lines.append('    }')
    lines.append('  }')
    lines.append('}')
    lines.append('')

    for role_name, policies in roles.items():
        tf_name = sanitize_tf_resource_name(role_name)
        lines.append(f'resource "aws_iam_role" "{tf_name}" {{')
        lines.append(f'  name               = "{role_name}"')
        lines.append('  assume_role_policy = data.aws_iam_policy_document.aam_trust.json')
        lines.append('')
        lines.append('  tags = {')
        lines.append('    ManagedBy = "AAM-Migration"')
        lines.append('  }')
        lines.append('}')
        lines.append('')

        # Managed policy attachments
        managed = [p for p in policies if p["policy_type"] != "Inline"]
        for i, p in enumerate(managed):
            attachment_name = f"{tf_name}_attach_{i}"
            if p["policy_type"] == "AWS Managed":
                arn = f"arn:aws:iam::aws:policy/{p['policy_name']}"
            else:
                arn = f"arn:aws:iam::${{data.aws_caller_identity.current.account_id}}:policy/{p['policy_name']}"

            lines.append(f'resource "aws_iam_role_policy_attachment" "{attachment_name}" {{')
            lines.append(f'  role       = aws_iam_role.{tf_name}.name')
            lines.append(f'  policy_arn = "{arn}"')
            lines.append('}')
            lines.append('')

        # Inline policies — placeholder
        inline = [p for p in policies if p["policy_type"] == "Inline"]
        for p in inline:
            inline_tf_name = sanitize_tf_resource_name(p["policy_name"])
            lines.append(f'resource "aws_iam_role_policy" "{tf_name}_{inline_tf_name}" {{')
            lines.append(f'  name   = "{p["policy_name"]}"')
            lines.append(f'  role   = aws_iam_role.{tf_name}.id')
            lines.append('  # TODO: Replace with actual inline policy JSON')
            lines.append('  policy = jsonencode({')
            lines.append('    Version = "2012-10-17"')
            lines.append('    Statement = [{')
            lines.append('      Sid      = "TODO"')
            lines.append('      Effect   = "Allow"')
            lines.append('      Action   = ["*"]')
            lines.append('      Resource = "*"')
            lines.append('    }]')
            lines.append('  })')
            lines.append('}')
            lines.append('')

    # Outputs
    lines.append('# Outputs')
    for role_name in roles:
        tf_name = sanitize_tf_resource_name(role_name)
        lines.append(f'output "{tf_name}_arn" {{')
        lines.append(f'  description = "ARN of {role_name}"')
        lines.append(f'  value       = aws_iam_role.{tf_name}.arn')
        lines.append('}')
        lines.append('')

    with open(output_file, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"  Terraform template:     {output_file}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_iac_templates.py <csv_file>")
        print("Example: python generate_iac_templates.py AAM_role_evaluation_760560298386.csv")
        sys.exit(1)

    csv_file = sys.argv[1]
    if not os.path.isfile(csv_file):
        print(f"Error: File not found: {csv_file}")
        sys.exit(1)

    print(f"Reading: {csv_file}")
    roles = parse_csv(csv_file)
    print(f"  Found {len(roles)} role(s)\n")

    if not roles:
        print("No roles found in CSV. Nothing to generate.")
        sys.exit(0)

    print("Generating IaC templates...")
    generate_cloudformation(roles, "aam_roles_cloudformation.yaml")
    generate_terraform(roles, "aam_roles_terraform.tf")

    print("\nDone. Review the generated files and update any TODO placeholders")
    print("(inline policy documents) before deploying.")


if __name__ == "__main__":
    main()
